=== mimmi20/browser-detector/schema/tests.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "array",
  "minItems": 1,
  "uniqueItems": true,
  "items": {
    "type": "object",
    "properties": {
      "headers": {
        "type": "object",
        "properties": {
          "user-agent": {
            "type": "string"
          }
        }
      },
      "device": {
        "type": "object",
        "properties": {
          "deviceName": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          },
          "marketingName": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          },
          "manufacturer": {
            "type": "string"
          },
          "brand": {
            "type": "string"
          },
          "dualOrientation": null,
    "simCount": null,
    "display": {
            "type": "object",
            "properties": {
              "width": {
                "anyOf": [
                  {
                    "type": "integer",
                    "minimum": 0
                  },
                  {
                    "type": "null"
                  }
                ]
              },
              "height": {
                "anyOf": [
                  {
                    "type": "integer",
                    "minimum": 0
                  },
                  {
                    "type": "null"
                  }
                ]
              },
              "touch": {
                "anyOf": [
                  {
                    "type": "boolean"
                  },
                  {
                    "type": "null"
                  }
                ]
              },
              "size": {
                "anyOf": [
                  {
                    "type": "number",
                    "minimum": 0
                  },
                  {
                    "type": "null"
                  }
                ]
              }
            },
            "required": [
              "width",
              "height",
              "touch",
              "size"
            ]
          },
          "type": {
            "type": "string"
          }
        },
        "required": [
          "deviceName",
          "marketingName",
          "manufacturer",
          "brand",
          "display",
          "type"
        ]
      },
      "browser": {
        "type": "object",
        "properties": {
          "name": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          },
          "modus": {
            "anyOf": [
              {
                "type": "null"
              },
              {
                "type": "integer"
              }
            ]
          },
          "version": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          },
          "manufacturer": {
            "type": "string"
          },
          "bits": {
            "anyOf": [
              {
                "type": "null"
              },
              {
                "type": "integer"
              }
            ]
          },
          "type": {
            "type": "string"
          }
        },
        "required": [
          "name",
          "modus",
          "version",
          "manufacturer",
          "bits",
          "type"
        ]
      },
      "os": {
        "type": "object",
        "properties": {
          "name": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          },
          "marketingName": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          },
          "version": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          },
          "manufacturer": {
            "type": "string"
          },
          "bits": {
            "anyOf": [
              {
                "type": "integer"
              },
              {
                "type": "null"
              }
            ]
          }
        },
        "required": [
          "name",
          "marketingName",
          "version",
          "manufacturer",
          "bits"
        ]
      },
      "engine": {
        "type": "object",
        "properties": {
          "name": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          },
          "version": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          },
          "manufacturer": {
            "type": "string"
          }
        },
        "required": [
          "name",
          "version",
          "manufacturer"
        ]
      }
    },
    "required": [
      "headers",
      "device",
      "browser",
      "os",
      "engine"
    ]
  }
}

=== mimmi20/browser-detector/tests/data/bird/smartphone.json
[
  {
    "headers": {
      "user-agent": "Bird-Doeasy E700_TD/S100 Linux/3.0.8 Android/4.0.3 Release/03.12.2013 Browser/AppleWebkit534.30 Mobile Safari/534.30;"
    },
    "device": {
      "deviceName": "E700",
      "marketingName": "E700",
      "manufacturer": "bird",
      "brand": "bird",
      "display": {
        "width": 320,
        "height": 240,
        "touch": true,
        "size": null
      },
      "type": "smartphone"
    },
    "browser": {
      "name": "Android Webkit",
      "modus": null,
      "version": "4.0.0",
      "manufacturer": "google",
      "bits": 32,
      "type": "browser"
    },
    "os": {
      "name": "Android",
      "marketingName": "Android",
      "version": "4.0.3",
      "manufacturer": "google",
      "bits": 32
    },
    "engine": {
      "name": "WebKit",
      "version": "534.30.0",
      "manufacturer": "apple"
    }
  },
  {
    "headers": {
      "user-agent": "Bird i600_TD/1.0 Linux/3.0.8 Android/4.0.3 Release/04.20.2013 AppleWebKit/534.30 Version/4.0 Mozilla/5.0 Mobile System/Android 4.0.3;"
    },
    "device": {
      "deviceName": "I600",
      "marketingName": "I600",
      "manufacturer": "bird",
      "brand": "bird",
      "display": {
        "width": 800,
        "height": 480,
        "touch": true,
        "size": null
      },
      "type": "smartphone"
    },
    "browser": {
      "name": "Android Webkit",
      "modus": null,
      "version": "4.0.0",
      "manufacturer": "google",
      "bits": 32,
      "type": "browser"
    },
    "os": {
      "name": "Android",
      "marketingName": "Android",
      "version": "4.0.3",
      "manufacturer": "google",
      "bits": 32
    },
    "engine": {
      "name": "WebKit",
      "version": "534.30.0",
      "manufacturer": "apple"
    }
  },
  {
    "headers": {
      "user-agent": "Mozilla/5.0 (Linux; U; Android 4.2.2; zh-cn; Bird i7 Build/JDQ39) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30Mopo/1830(4.0.12;1_skymobi_;bd87_89_td_emmc_bird_i7;Bird i7;480*854)"
    },
    "device": {
      "deviceName": "I7",
      "marketingName": "I7",
      "manufacturer": "bird",
      "brand": "bird",
      "display": {
        "width": 854,
        "height": 480,
        "touch": true,
        "size": null
      },
      "type": "smartphone"
    },
    "browser": {
      "name": "Android Webkit",
      "modus": null,
      "version": "4.0.0",
      "manufacturer": "google",
      "bits": 32,
      "type": "browser"
    },
    "os": {
      "name": "Android",
      "marketingName": "Android",
      "version": "4.2.2",
      "manufacturer": "google",
      "bits": 32
    },
    "engine": {
      "name": "WebKit",
      "version": "534.30.0",
      "manufacturer": "apple"
    }
  },
  {
    "headers": {
      "user-agent": "Mozilla/5.0 (Linux; U; Android 4.0.4; zh-CN; BIRD T900 Build/MocorDroid4.0.4) AppleWebKit/534.31 (KHTML, like Gecko) UCBrowser/9.2.3.324 U3/0.8.0 Mobile Safari/534.31"
    },
    "device": {
      "deviceName": "T900",
      "marketingName": "T900",
      "manufacturer": "bird",
      "brand": "bird",
      "display": {
        "width": 480,
        "height": 320,
        "touch": true,
        "size": null
      },
      "type": "smartphone"
    },
    "browser": {
      "name": "UC Browser",
      "modus": null,
      "version": "9.2.3.324",
      "manufacturer": "ucweb",
      "bits": 32,
      "type": "transcoder"
    },
    "os": {
      "name": "Android",
      "marketingName": "Android",
      "version": "4.0.4",
      "manufacturer": "google",
      "bits": 32
    },
    "engine": {
      "name": "U3",
      "version": "0.8.0",
      "manufacturer": "ucweb"
    }
  },
  {
    "headers": {
      "user-agent": "Bird_T9108_TD/T9108_V1.00 Android/2.3.5 SC8810_CMCC/W12.06.10 Release/04.18.2012 Browser/AppleWebKit533.1"
    },
    "device": {
      "deviceName": "T9108",
      "marketingName": "T9108",
      "manufacturer": "bird",
      "brand": "bird",
      "display": {
        "width": 480,
        "height": 320,
        "touch": true,
        "size": null
      },
      "type": "smartphone"
    },
    "browser": {
      "name": "Darwin Browser",
      "modus": null,
      "version": "0.0.0",
      "manufacturer": "unknown",
      "bits": 32,
      "type": "browser"
    },
    "os": {
      "name": "Android",
      "marketingName": "Android",
      "version": "2.3.5",
      "manufacturer": "google",
      "bits": 32
    },
    "engine": {
      "name": "WebKit",
      "version": "533.1.0",
      "manufacturer": "apple"
    }
  },
  {
    "headers": {
      "user-agent": "Mozilla/5.0 (Linux; U; Android 4.0.3; fr-fr; BIRD-V8 Build/AD35) AppleWebKit/533.1 (KHTML, like Gecko) Version/4.0 Mobile Safari/533.1"
    },
    "device": {
      "deviceName": "V8",
      "marketingName": "V8",
      "manufacturer": "bird",
      "brand": "bird",
      "display": {
        "width": null,
        "height": null,
        "touch": true,
        "size": null
      },
      "type": "smartphone"
    },
    "browser": {
      "name": "Android Webkit",
      "modus": null,
      "version": "4.0.0",
      "manufacturer": "google",
      "bits": 32,
      "type": "browser"
    },
    "os": {
      "name": "Android",
      "marketingName": "Android",
      "version": "4.0.3",
      "manufacturer": "google",
      "bits": 32
    },
    "engine": {
      "name": "WebKit",
      "version": "533.1.0",
      "manufacturer": "apple"
    }
  },
  {
    "headers": {
      "user-agent": "Mozilla/5.0 (Linux; U; Android 4.2.2; en-us; BIRD_W5 Build/JDQ39) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30"
    },
    "device": {
      "deviceName": "W5",
      "marketingName": "W5",
      "manufacturer": "bird",
      "brand": "bird",
      "display": {
        "width": 480,
        "height": 320,
        "touch": true,
        "size": null
      },
      "type": "smartphone"
    },
    "browser": {
      "name": "Android Webkit",
      "modus": null,
      "version": "4.0.0",
      "manufacturer": "google",
      "bits": 32,
      "type": "browser"
    },
    "os": {
      "name": "Android",
      "marketingName": "Android",
      "version": "4.2.2",
      "manufacturer": "google",
      "bits": 32
    },
    "engine": {
      "name": "WebKit",
      "version": "534.30.0",
      "manufacturer": "apple"
    }
  },
  {
    "headers": {
      "user-agent": "Bird_T900/1.0 WindowsMobile/6.5 Release/12.1.2010 Browser/IE6 Profile/MIDP-2.0 Configuration/CLDC-1.1"
    },
    "device": {
      "deviceName": "T900",
      "marketingName": "T900",
      "manufacturer": "bird",
      "brand": "bird",
      "display": {
        "width": 480,
        "height": 320,
        "touch": true,
        "size": null
      },
      "type": "smartphone"
    },
    "browser": {
      "name": null,
      "modus": null,
      "version": "0.0.0",
      "manufacturer": "unknown",
      "bits": 32,
      "type": "unknown"
    },
    "os": {
      "name": "Android",
      "marketingName": "Android",
      "version": "0.0.0",
      "manufacturer": "google",
      "bits": 32
    },
    "engine": {
      "name": null,
      "version": "0.0.0",
      "manufacturer": "unknown"
    }
  }
]

=== mimmi20/browser-detector/tests/data/turbopad/smartphone.json
[
  {
    "headers": {
      "user-agent": "Mozilla/5.0 (Linux; U; Android 4.2.1; ru-ru; Turbo Pad 500 Build/JOP40D) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30 ACHEETAHI/2100501028"
    },
    "device": {
      "deviceName": "Pad 500",
      "marketingName": "Pad 500",
      "manufacturer": "TurboPad",
      "brand": "TurboPad",
      "display": {
        "width": 1280,
        "height": 720,
        "touch": true,
        "size": null
      },
      "type": "smartphone"
    },
    "browser": {
      "name": "CM Browser",
      "modus": null,
      "version": "0.0.0",
      "manufacturer": "CheetahMobile",
      "bits": 32,
      "type": "browser"
    },
    "os": {
      "name": "Android",
      "marketingName": "Android",
      "version": "4.2.1",
      "manufacturer": "Google",
      "bits": 32
    },
    "engine": {
      "name": "WebKit",
      "version": "534.30.0",
      "manufacturer": "Apple"
    }
  },
  {
    "headers": {
      "user-agent": "Mozilla/5.0 (Linux; U; Android 4.2.1; ru-ru; Turbo X6 Build/JOP40D) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30 ACHEETAHI/2100501028"
    },
    "device": {
      "deviceName": "Turbo X6",
      "marketingName": "Turbo X6",
      "manufacturer": "TurboPad",
      "brand": "TurboPad",
      "display": {
        "width": 1920,
        "height": 1080,
        "touch": true,
        "size": null
      },
      "type": "smartphone"
    },
    "browser": {
      "name": "CM Browser",
      "modus": null,
      "version": "0.0.0",
      "manufacturer": "CheetahMobile",
      "bits": 32,
      "type": "browser"
    },
    "os": {
      "name": "Android",
      "marketingName": "Android",
      "version": "4.2.1",
      "manufacturer": "Google",
      "bits": 32
    },
    "engine": {
      "name": "WebKit",
      "version": "534.30.0",
      "manufacturer": "Apple"
    }
  }
]

=== mimmi20/browser-detector/tests/data/advan/tablet.json
[
  {
    "headers": {
      "user-agent": "Mozilla/5.0 (Linux; Android 4.4.2; ADVAN T1L Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/30.0.0.0 Mobile Safari/537.36"
    },
    "device": {
      "deviceName": "T1L",
      "marketingName": "T1L",
      "manufacturer": "advan",
      "brand": "advan",
      "display": {
        "width": 800,
        "height": 480,
        "touch": true,
        "size": null
      },
      "type": "tablet"
    },
    "browser": {
      "name": "Android WebView",
      "modus": null,
      "version": "30.0.0.0",
      "manufacturer": "google",
      "bits": 32,
      "type": "browser"
    },
    "os": {
      "name": "Android",
      "marketingName": "Android",
      "version": "4.4.2",
      "manufacturer": "google",
      "bits": 32
    },
    "engine": {
      "name": "Blink",
      "version": "537.36.0",
      "manufacturer": "google"
    }
  },
  {
    "headers": {
      "user-agent": "Mozilla/5.0 (Linux; U; Android 4.0.4; en-us; ANDROID T3i Build/IMM76D) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30"
    },
    "device": {
      "deviceName": "T3i",
      "marketingName": "Vandroid T3I",
      "manufacturer": "advan",
      "brand": "advan",
      "display": {
        "width": null,
        "height": null,
        "touch": true,
        "size": 9.7
      },
      "type": "tablet"
    },
    "browser": {
      "name": "Android Webkit",
      "modus": null,
      "version": "4.0.0",
      "manufacturer": "google",
      "bits": 32,
      "type": "browser"
    },
    "os": {
      "name": "Android",
      "marketingName": "Android",
      "version": "4.0.4",
      "manufacturer": "google",
      "bits": 32
    },
    "engine": {
      "name": "WebKit",
      "version": "534.30.0",
      "manufacturer": "apple"
    }
  }
]

=== mimmi20/browser-detector/tests/data/star-way/fone-pad.json
[
  {
    "headers": {
      "user-agent": "Mozilla/5.0 (Linux; Android 4.0.4; STARWAY Andromeda S925 3G Build/IMM76D) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/38.0.2125.102 Safari/537.36 OPR/25.0.1619.84037"
    },
    "device": {
      "deviceName": "Andromeda S925 3G",
      "marketingName": "Andromeda S925 3G",
      "manufacturer": "star-way",
      "brand": "star-way",
      "display": {
        "width": 1024,
        "height": 768,
        "touch": true,
        "size": null
      },
      "type": "fone-pad"
    },
    "browser": {
      "name": "Opera Mobile",
      "modus": null,
      "version": "25.0.1619.84037",
      "manufacturer": "opera",
      "bits": null,
      "type": "browser"
    },
    "os": {
      "name": "Android",
      "marketingName": "Android",
      "version": "4.0.4",
      "manufacturer": "google",
      "bits": null
    },
    "engine": {
      "name": "Blink",
      "version": "537.36.0",
      "manufacturer": "google"
    }
  }
]

=== mimmi20/browser-detector/tests/data/xgimi/tv-media-player.json
[
  {
    "headers": {
      "user-agent": "Dalvik/2.1.0 (Linux## U## Android 5.1.1## XGIMI TV Build/LMY47V)"
    },
    "device": {
      "deviceName": "TV",
      "marketingName": "TV",
      "manufacturer": "XGIMI",
      "brand": "XGIMI",
      "display": {
        "width": null,
        "height": null,
        "touch": false,
        "size": null
      },
      "type": "tv-media-player"
    },
    "browser": {
      "name": "Dalvik",
      "modus": null,
      "version": "2.1.0",
      "manufacturer": "google",
      "bits": 32,
      "type": "application"
    },
    "os": {
      "name": "Android",
      "marketingName": "Android",
      "version": "5.1.1",
      "manufacturer": "google",
      "bits": 32
    },
    "engine": {
      "name": "WebKit",
      "version": "0.0.0",
      "manufacturer": "apple"
    }
  }
]
